# Generated by Django 4.1.6 on 2023-02-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funkcja",
            fields=[
                ("funkcjaId", models.IntegerField(primary_key=True, serialize=False)),
                ("nazwa", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "typ_funkcji",
                    models.IntegerField(choices=[(2, "Rada"), (1, "Komisja")]),
                ),
                ("opis_typ", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Komisja",
            fields=[
                ("komisjaId", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "nazwaKomisji",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "przedmiot_dzialania",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                ("zadania", models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OkregWyborczy",
            fields=[
                ("okregId", models.IntegerField(primary_key=True, serialize=False)),
                ("nrOkregu", models.IntegerField()),
                ("okreg", models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="Osoba",
            fields=[
                ("osobaId", models.IntegerField(primary_key=True, serialize=False)),
                ("nazwa", models.CharField(max_length=350)),
                ("imie", models.CharField(max_length=150)),
                ("nazwisko", models.CharField(max_length=250)),
                ("email", models.CharField(blank=True, max_length=350, null=True)),
                ("tel", models.CharField(blank=True, max_length=20, null=True)),
                ("www", models.CharField(blank=True, max_length=3500, null=True)),
                ("img_path", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Radny",
            fields=[
                ("radnyId", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "okregId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dzielnia.okregwyborczy",
                    ),
                ),
                (
                    "osobaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dzielnia.osoba"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkladRady",
            fields=[
                ("skladRadyId", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "funkcjaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dzielnia.funkcja",
                    ),
                ),
                (
                    "radnyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dzielnia.radny"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkladKomisji",
            fields=[
                (
                    "skladkomisjiId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "funkcjaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dzielnia.funkcja",
                    ),
                ),
                (
                    "komisjaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dzielnia.komisja",
                    ),
                ),
                (
                    "radnyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dzielnia.radny"
                    ),
                ),
            ],
        ),
    ]
