# Generated by Django 4.1.6 on 2023-02-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzielnia', '0002_komisja_dzien_komisja_godzina_komisja_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komisja',
            name='dzien',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='komisja',
            name='godzina',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
