# Generated by Django 4.1.6 on 2023-02-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzielnia', '0003_alter_komisja_dzien_alter_komisja_godzina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komisja',
            name='nazwaKomisji',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='komisja',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
