# Generated by Django 4.1.6 on 2023-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzielnia', '0004_alter_komisja_nazwakomisji_alter_komisja_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komisja',
            name='przedmiot_dzialania',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='komisja',
            name='zadania',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
