# Generated by Django 4.1.6 on 2023-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzielnia', '0005_alter_komisja_przedmiot_dzialania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komisja',
            name='przedmiot_dzialania',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
