# Generated by Django 4.1.6 on 2023-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzielnia', '0006_alter_komisja_przedmiot_dzialania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funkcja',
            name='funkcjaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='komisja',
            name='komisjaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='okregwyborczy',
            name='okregId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='osobaId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radny',
            name='radnyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skladkomisji',
            name='skladkomisjiId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skladrady',
            name='skladRadyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
